### ISSUE TITLE
the sys_info command leaves behind a running transient dummy VM

### ISSUE THREAD

**Issue by eskultety** [AMDESE/sev-tool#16] opened 2019-10-10 10:45 UTC
Upon the successfull completion of the
`./src/sevtool --sys_info` command, a transient VM with created by the tool is left behind in the running state.

```
$ virsh list --all
 Id   Name             State
---------------------------------
 11   fceac9812431d1   running
```

**Comment by mickys** [comment] 2019-10-18 09:44
what are you running this on ? 
- hardware, bios version, sev firmware version / os / kernel / options.

**Comment by ldeweysuse** [comment] 2020-02-10 17:39
This is likely because of the difficulty in checking the status of OVMF. I have added some additional logic in a [pull request](https://github.com/AMDESE/sev-tool/pull/21) to hopefully address this problem.

**Comment by lilienbm** [comment] 2021-04-23 16:38
@larrydewey 's pull request is closed. Closing this ticket; please re-open if the issue is not fixed

**Closed by lilienbm** 2021-04-23 16:38 UTC
